var annotated_dup =
[
    [ "planc", null, [
      [ "AOADMMNMF", "classplanc_1_1AOADMMNMF.html", "classplanc_1_1AOADMMNMF" ],
      [ "AUNTF", "classplanc_1_1AUNTF.html", "classplanc_1_1AUNTF" ],
      [ "BPPNMF", "classplanc_1_1BPPNMF.html", "classplanc_1_1BPPNMF" ],
      [ "DistALS", "classplanc_1_1DistALS.html", "classplanc_1_1DistALS" ],
      [ "DistANLSBPP", "classplanc_1_1DistANLSBPP.html", "classplanc_1_1DistANLSBPP" ],
      [ "DistAOADMM", "classplanc_1_1DistAOADMM.html", "classplanc_1_1DistAOADMM" ],
      [ "DistAUNMF", "classplanc_1_1DistAUNMF.html", "classplanc_1_1DistAUNMF" ],
      [ "DistAUNTF", "classplanc_1_1DistAUNTF.html", "classplanc_1_1DistAUNTF" ],
      [ "DistHALS", "classplanc_1_1DistHALS.html", "classplanc_1_1DistHALS" ],
      [ "DistIO", "classplanc_1_1DistIO.html", "classplanc_1_1DistIO" ],
      [ "DistMU", "classplanc_1_1DistMU.html", "classplanc_1_1DistMU" ],
      [ "DistNaiveANLSBPP", "classplanc_1_1DistNaiveANLSBPP.html", "classplanc_1_1DistNaiveANLSBPP" ],
      [ "DistNMF", "classplanc_1_1DistNMF.html", "classplanc_1_1DistNMF" ],
      [ "DistNMF1D", "classplanc_1_1DistNMF1D.html", "classplanc_1_1DistNMF1D" ],
      [ "DistNMFDriver", "classplanc_1_1DistNMFDriver.html", "classplanc_1_1DistNMFDriver" ],
      [ "DistNMFTime", "classplanc_1_1DistNMFTime.html", "classplanc_1_1DistNMFTime" ],
      [ "DistNTF", "classplanc_1_1DistNTF.html", "classplanc_1_1DistNTF" ],
      [ "DistNTFANLSBPP", "classplanc_1_1DistNTFANLSBPP.html", "classplanc_1_1DistNTFANLSBPP" ],
      [ "DistNTFAOADMM", "classplanc_1_1DistNTFAOADMM.html", "classplanc_1_1DistNTFAOADMM" ],
      [ "DistNTFCPALS", "classplanc_1_1DistNTFCPALS.html", "classplanc_1_1DistNTFCPALS" ],
      [ "DistNTFHALS", "classplanc_1_1DistNTFHALS.html", "classplanc_1_1DistNTFHALS" ],
      [ "DistNTFIO", "classplanc_1_1DistNTFIO.html", "classplanc_1_1DistNTFIO" ],
      [ "DistNTFMU", "classplanc_1_1DistNTFMU.html", "classplanc_1_1DistNTFMU" ],
      [ "DistNTFNES", "classplanc_1_1DistNTFNES.html", "classplanc_1_1DistNTFNES" ],
      [ "DistNTFTime", "classplanc_1_1DistNTFTime.html", "classplanc_1_1DistNTFTime" ],
      [ "HALSNMF", "classplanc_1_1HALSNMF.html", "classplanc_1_1HALSNMF" ],
      [ "LUC", "classplanc_1_1LUC.html", "classplanc_1_1LUC" ],
      [ "MPICommunicator", "classplanc_1_1MPICommunicator.html", "classplanc_1_1MPICommunicator" ],
      [ "MUNMF", "classplanc_1_1MUNMF.html", "classplanc_1_1MUNMF" ],
      [ "NCPFactors", "classplanc_1_1NCPFactors.html", "classplanc_1_1NCPFactors" ],
      [ "NMF", "classplanc_1_1NMF.html", "classplanc_1_1NMF" ],
      [ "NTFANLSBPP", "classplanc_1_1NTFANLSBPP.html", "classplanc_1_1NTFANLSBPP" ],
      [ "NTFAOADMM", "classplanc_1_1NTFAOADMM.html", "classplanc_1_1NTFAOADMM" ],
      [ "NTFDriver", "classplanc_1_1NTFDriver.html", "classplanc_1_1NTFDriver" ],
      [ "NTFHALS", "classplanc_1_1NTFHALS.html", "classplanc_1_1NTFHALS" ],
      [ "NTFMPICommunicator", "classplanc_1_1NTFMPICommunicator.html", "classplanc_1_1NTFMPICommunicator" ],
      [ "NTFMU", "classplanc_1_1NTFMU.html", "classplanc_1_1NTFMU" ],
      [ "NTFNES", "classplanc_1_1NTFNES.html", "classplanc_1_1NTFNES" ],
      [ "NumPyArray", "classplanc_1_1NumPyArray.html", "classplanc_1_1NumPyArray" ],
      [ "ParseCommandLine", "classplanc_1_1ParseCommandLine.html", "classplanc_1_1ParseCommandLine" ],
      [ "Tensor", "classplanc_1_1Tensor.html", "classplanc_1_1Tensor" ]
    ] ],
    [ "ActiveSetNNLS", "classActiveSetNNLS.html", "classActiveSetNNLS" ],
    [ "BooleanArrayComparator", "classBooleanArrayComparator.html", "classBooleanArrayComparator" ],
    [ "BPPNNLS", "classBPPNNLS.html", "classBPPNNLS" ],
    [ "DenseDimensionTree", "classDenseDimensionTree.html", "classDenseDimensionTree" ],
    [ "NNLS", "classNNLS.html", "classNNLS" ],
    [ "SortBooleanMatrix", "classSortBooleanMatrix.html", "classSortBooleanMatrix" ]
];